import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";
import FinalCTA from "../../../components/FinalCTA";
import { ArrowRight } from "../../../components/icons";
import { getDictionary, hasLocale } from "../../dictionaries";
import { blogPosts, findPostIndex } from "../blog-data";

// `[lang]` is generated by the parent layout, so this leaf only needs slugs.
export function generateStaticParams() {
  return blogPosts.map((post) => ({ slug: post.slug }));
}

export async function generateMetadata({ params }) {
  const { lang, slug } = await params;
  if (!hasLocale(lang)) return {};
  const idx = findPostIndex(slug);
  if (idx === -1) return {};
  const dict = await getDictionary(lang);
  const post = dict.blogPage.posts[idx];
  return { title: post.title, description: post.excerpt };
}

export default async function BlogPostPage({ params }) {
  const { lang, slug } = await params;
  if (!hasLocale(lang)) notFound();

  const idx = findPostIndex(slug);
  if (idx === -1) notFound();

  const dict = await getDictionary(lang);
  const t = dict.blogPage;
  const post = t.posts[idx];
  const meta = blogPosts[idx];

  // Up to three other posts for the "related reading" strip
  const related = t.posts
    .map((p, i) => ({ p, i }))
    .filter(({ i }) => i !== idx)
    .slice(0, 3);

  return (
    <div className="relative">
      <Navbar />
      <main>
        {/* Article header */}
        <section className="relative overflow-hidden bg-primary-dark">
          <Image
            src={meta.image}
            alt=""
            fill
            priority
            sizes="100vw"
            className="object-cover opacity-30"
          />
          <div className="absolute inset-0 bg-linear-to-b from-primary-dark/70 via-primary-dark/80 to-primary-dark" />
          <div className="relative mx-auto max-w-3xl px-6 pb-16 pt-36 text-center lg:pb-20 lg:pt-44">
            <span className="inline-block rounded-full bg-cta px-3.5 py-1.5 text-xs font-semibold text-white shadow-sm">
              {post.tag}
            </span>
            <h1 className="mx-auto mt-5 max-w-2xl font-display text-3xl font-bold leading-[1.12] text-white sm:text-4xl lg:text-5xl">
              {post.title}
            </h1>
            <div className="mt-6 flex items-center justify-center gap-3 text-sm text-white/70">
              <span>{post.date}</span>
              <span className="h-1 w-1 rounded-full bg-white/40" />
              <span>{post.read}</span>
            </div>
            <nav className="mt-6 flex items-center justify-center gap-2 text-sm text-white/60">
              <Link href={`/${lang}`} className="transition-colors hover:text-white">
                {dict.pageHeader.home}
              </Link>
              <span>/</span>
              <Link href={`/${lang}/blog`} className="transition-colors hover:text-white">
                {t.breadcrumb}
              </Link>
            </nav>
          </div>
        </section>

        {/* Article body */}
        <article className="bg-white">
          <div className="mx-auto max-w-3xl px-6 py-16 lg:py-20">
            <p className="text-lg font-medium leading-relaxed text-slate-700">
              {post.excerpt}
            </p>
            <div className="mt-6 space-y-5 text-base leading-relaxed text-slate-600">
              {post.body.map((para, i) => (
                <p key={i}>{para}</p>
              ))}
            </div>

            <div className="mt-12 border-t border-slate-100 pt-8">
              <Link
                href={`/${lang}/blog`}
                className="inline-flex items-center gap-2 text-sm font-semibold text-primary transition-colors hover:text-primary-dark"
              >
                <ArrowRight className="h-4 w-4 rotate-180 rtl:rotate-0" />
                {t.backToBlog}
              </Link>
            </div>
          </div>
        </article>

        {/* Related reading */}
        <section className="bg-surface">
          <div className="mx-auto max-w-7xl px-6 py-20 lg:px-10">
            <h2 className="font-display text-2xl font-bold text-slate-900 sm:text-3xl">
              {t.relatedReading}
            </h2>
            <div className="mt-8 grid gap-8 md:grid-cols-3">
              {related.map(({ p, i }) => (
                <Link
                  key={p.title}
                  href={`/${lang}/blog/${blogPosts[i].slug}`}
                  className="group flex flex-col overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-card transition-shadow duration-300 hover:shadow-lift"
                >
                  <div className="relative h-44 overflow-hidden">
                    <Image
                      src={blogPosts[i].image}
                      alt=""
                      fill
                      sizes="(max-width: 768px) 100vw, 33vw"
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                    />
                    <span className="absolute left-4 top-4 rounded-full bg-cta px-3.5 py-1.5 text-xs font-semibold text-white shadow-sm">
                      {p.tag}
                    </span>
                  </div>
                  <div className="flex flex-1 flex-col p-6">
                    <div className="flex items-center gap-3 text-xs font-medium text-slate-400">
                      <span>{p.date}</span>
                      <span className="h-1 w-1 rounded-full bg-slate-300" />
                      <span>{p.read}</span>
                    </div>
                    <h3 className="mt-3 font-display text-lg font-bold leading-snug text-slate-900 transition-colors duration-200 group-hover:text-primary">
                      {p.title}
                    </h3>
                    <span className="mt-5 inline-flex w-fit items-center gap-2 text-sm font-semibold text-primary transition-colors duration-200 group-hover:text-primary-dark">
                      {t.readMore}
                      <ArrowRight className="h-4 w-4 transition-transform duration-200 group-hover:translate-x-0.5 rtl:rotate-180 rtl:group-hover:-translate-x-0.5 rtl:group-hover:translate-x-0" />
                    </span>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>

        <FinalCTA dict={dict} />
      </main>
      <Footer dict={dict} lang={lang} />
    </div>
  );
}
